// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp9YLVwi2G7umxplPeXlm4llAyjLjL8t8',
    appId: '1:156956621189:web:add6d334853126ff7c6cec',
    messagingSenderId: '156956621189',
    projectId: 'personalfinance-2859d',
    authDomain: 'personalfinance-2859d.firebaseapp.com',
    storageBucket: 'personalfinance-2859d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8JjoN65vWukfVvLA-JuVQXHjY0BiY1Dk',
    appId: '1:156956621189:android:a23fee425a326f8d7c6cec',
    messagingSenderId: '156956621189',
    projectId: 'personalfinance-2859d',
    storageBucket: 'personalfinance-2859d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBffO4uZiTcrrF4VKv_E2D4gOjRupysyF0',
    appId: '1:156956621189:ios:cbe9141dcc7d55367c6cec',
    messagingSenderId: '156956621189',
    projectId: 'personalfinance-2859d',
    storageBucket: 'personalfinance-2859d.appspot.com',
    iosBundleId: 'com.example.personalFinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBffO4uZiTcrrF4VKv_E2D4gOjRupysyF0',
    appId: '1:156956621189:ios:b97420ccdaf014d07c6cec',
    messagingSenderId: '156956621189',
    projectId: 'personalfinance-2859d',
    storageBucket: 'personalfinance-2859d.appspot.com',
    iosBundleId: 'com.example.personalFinance.RunnerTests',
  );
}
